# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3c9cf734c1e7bb7f77f5deedd4bf88e88809a5aaea437083a22e427458843fac713720f9e8816dbf0ac72b937815184dafa4a00a27ccdd034f72688320fea3

test:
  secret_key_base: bc19b2105917e7421842fb6d3fcf17d19b17477184028794b2f926e6be223a88dd19f0a4ca0ff32a0b1054c16c7caa00623475c1ef04d86fabb8fb075869d9f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
